[features]
seeds = false
skip-lint = false
[programs.localnet]
cushion = "2rYUpCQGEqxz8WesY44kkXm1JvtWairzVJLjhf2UpynL"

[registry]
url = "https://api.apr.dev"

[test.validator]
url = "https://api.mainnet-beta.solana.com"
[[test.validator.clone]] # Pyth SOL/USD feed
address = "H6ARHf6YXhGYeQfUzQNGk6rDNnLBQKrenN712K4AQJEG"

[provider]
cluster = "Localnet"
wallet = "./id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
